<a href="https://colab.research.google.com/github/Omarctr/Machine-Learning/blob/main/hyperparemeters_GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [ ]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['iris'] = iris.target
df['name'] = df.iris.apply(lambda x : iris.target_names[x])
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),iris,name
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,virginica
146,6.3,2.5,5.0,1.9,2,virginica
147,6.5,3.0,5.2,2.0,2,virginica
148,6.2,3.4,5.4,2.3,2,virginica
149,5.9,3.0,5.1,1.8,2,virginica

In [ ]:
from sklearn.model_selection import train_test_split
x = df.drop(columns = ['iris', 'name'])
y = df.iris

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [ ]:
from sklearn.svm import SVC
svc = SVC(kernel = 'rbf', C = 30, gamma = 'auto')
svc.fit(x_train, y_train)
svc.score(x_test, y_test)

1.0

In [ ]:
from sklearn.model_selection import cross_val_score

cross_val_score(SVC(kernel = 'linear', C = 30), x, y, cv = 5)

array([1. , 1. , 0.9, 0.9, 1. ])

In [ ]:
cross_val_score(SVC(kernel = 'poly', C = 10, gamma = 'auto'), x, y, cv = 5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [ ]:
cross_val_score(SVC(kernel = 'rbf', C = 10), x, y, cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

# **other way**

In [ ]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(SVC(gamma = 'auto'), {
    'C' : [1, 10, 20, 30],
    'kernel' : ['rbf', 'linear', 'poly']
}, cv = 5)

In [ ]:
clf.fit(x, y)
clf.cv_results_

{'mean_fit_time': array([0.00564108, 0.00522318, 0.00819259, 0.00571265, 0.00531144,
        0.01068273, 0.00533504, 0.00509663, 0.0173059 , 0.00523872,
        0.00303049, 0.01061482]),
 'std_fit_time': array([0.0013833 , 0.00145642, 0.00237528, 0.00205087, 0.00041866,
        0.00452532, 0.00084267, 0.00117041, 0.01183993, 0.00351302,
        0.00027229, 0.00661349]),
 'mean_score_time': array([0.00393276, 0.00495176, 0.00446701, 0.00460467, 0.00423231,
        0.00417237, 0.00429592, 0.00338821, 0.00437202, 0.00272555,
        0.00210395, 0.00231681]),
 'std_score_time': array([1.87040220e-03, 2.77527796e-03, 1.00454581e-03, 2.34302304e-03,
        8.97204214e-04, 7.43427820e-05, 1.18120619e-03, 1.92485843e-04,
        1.42810053e-03, 9.26399673e-04, 1.25762544e-04, 3.37798612e-04]),
 'param_C': masked_array(data=[1, 1, 1, 10, 10, 10, 20, 20, 20, 30, 30, 30],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'poly', 'rbf', 'linear', 'poly',
                    'rbf', 'linear', 'poly', 'rbf', 'linear', 'poly'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'poly'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'poly'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'poly'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'poly'}],
 'split0_test_score': array([0.96666667, 0.96666667, 1.        , 0.96666667, 1.        ,
        1.        , 0.96666667, 1.        , 0.96666667, 0.96666667,
        1.        , 0.96666667]),
 'split1_test_score': array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.96666667, 1.        ,
        1.        , 0.96666667]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.9       , 0.96666667, 0.9       ,
        0.9       , 0.9       , 0.9       , 0.9       , 0.9       ,
        0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.96666667,
        0.93333333, 0.96666667, 0.93333333, 0.93333333, 0.93333333,
        0.9       , 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.96666667, 0.98      , 0.97333333,
        0.96666667, 0.96666667, 0.96666667, 0.95333333, 0.96      ,
        0.96      , 0.95333333]),
 'std_test_score': array([0.01632993, 0.01632993, 0.0421637 , 0.01632993, 0.03887301,
        0.0421637 , 0.03651484, 0.0421637 , 0.03399346, 0.03887301,
        0.04898979, 0.03399346]),
 'rank_test_score': array([ 1,  1,  6,  1,  4,  6,  5,  6, 11,  9,  9, 11], dtype=int32)}

In [ ]:
res = pd.DataFrame(clf.cv_results_)
res

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005641,0.001383,0.003933,0.001870,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.005223,0.001456,0.004952,0.002775,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.008193,0.002375,0.004467,0.001005,1,poly,"{'C': 1, 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
3,0.005713,0.002051,0.004605,0.002343,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
4,0.005311,0.000419,0.004232,0.000897,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
5,0.010683,0.004525,0.004172,0.000074,10,poly,"{'C': 10, 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.005335,0.000843,0.004296,0.001181,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
7,0.005097,0.001170,0.003388,0.000192,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
8,0.017306,0.011840,0.004372,0.001428,20,poly,"{'C': 20, 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,11
9,0.005239,0.003513,0.002726,0.000926,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,9
10,0.003030,0.000272,0.002104,0.000126,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,9
11,0.010615,0.006613,0.002317,0.000338,30,poly,"{'C': 30, 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,11

In [ ]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

rs = RandomizedSearchCV(SVC(gamma = 'auto'), {
    'C' : [1, 10, 20],
    'kernel' : ['rbf', 'poly', 'linear']
}, cv = 5, n_iter = 2)

rs.fit(x, y)
result = pd.DataFrame(rs.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002757,0.000348,0.002005,0.000417,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.006000,0.003367,0.001984,0.000118,poly,10,"{'kernel': 'poly', 'C': 10}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,2

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier


model_params = {
    'svc' : {'model' : SVC(),
            'params' : {'C' : [10, 20, 30],
                        'kernel' : ['rbf', 'linear']}
             },
    'random forest' : {'model' : RandomForestClassifier(),
                       'params' : {'n_estimators' : [100, 150, 200]}
                       },
    'logistic regression' : {'model' : LogisticRegression(max_iter = 1000),
                             'params' : {'C' : [10, 20, 30]}
                             }
}

scores = []
for model_name, vals in model_params.items():
  mod = GridSearchCV(vals['model'], vals['params'], cv = 5, return_train_score = False)
  mod.fit(x, y)
  scores.append({
      'model' : model_name,
      'best_score' : mod.best_score_,
      'best_parameters' : mod.best_params_
  })


model_table = pd.DataFrame(scores)
model_table

                 model  best_score             best_parameters
0                  svc    0.980000  {'C': 10, 'kernel': 'rbf'}
1        random forest    0.966667       {'n_estimators': 150}
2  logistic regression    0.980000                   {'C': 30}

In [ ]:
from sklearn.datasets import load_digits

dig = load_digits()
df = pd.DataFrame(dig.data, columns = dig.feature_names)
df['digit'] = dig.target

In [ ]:
df
x = df.drop(columns = 'digit')
y = df.digit

In [ ]:
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
model_params = {
    'svc' : {'model' : SVC(),
            'params' : {'C' : [10, 20, 30],
                        'kernel' : ['rbf', 'linear']}
             },
    'random forest' : {'model' : RandomForestClassifier(),
                       'params' : {'n_estimators' : [100, 150, 200]}
                       },
    'logistic regression' : {'model' : LogisticRegression(max_iter = 1000),
                             'params' : {'C' : [10, 20, 30]}
                             },
    'gaussian naive bayes' : {'model' : GaussianNB(),
                              'params' : {'var_smoothing' : [1e-9]}},
    'bernoulli naive bayes' : {'model' : BernoulliNB(),
                               'params' :{'fit_prior' : [False, True],
                                          'force_alpha' : [False, True]}},
    'multinomial naive bayes' : {'model' : MultinomialNB(),
                                 'params' : {'fit_prior' : [False, True],
                                             'alpha' : [1, 5, 10 ,20]}}
}

adv_scores = []
for model_name , val in model_params.items():
  clf = GridSearchCV(val['model'], val['params'], cv = 5, return_train_score = False)
  clf.fit(x, y)
  adv_scores.append({
      'model_name' : model_name,
      'best_score' : clf.best_score_,
      'best_parameters' : clf.best_params_
  })


  model_table = pd.DataFrame(adv_scores)
  model_table

In [ ]:
model_table

,model_name,best_score,best_parameters
0,svc,0.973850,"{'C': 10, 'kernel': 'rbf'}"
1,random forest,0.939358,{'n_estimators': 150}
2,logistic regression,0.911543,{'C': 30}
3,gaussian naive bayes,0.806928,{'var_smoothing': 1e-09}
4,bernoulli naive bayes,0.824174,"{'fit_prior': False, 'force_alpha': False}"
5,multinomial naive bayes,0.874246,"{'alpha': 10, 'fit_prior': False}"

In [ ]:
ga = MultinomialNB(fit_prior=False, alpha = 1)
ga.fit(x, y)
ga.score(x, y)

0.9053978853644964