<a href="https://colab.research.google.com/github/Omarctr/Machine-Learning/blob/main/linear_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('/homeprices (1).csv')
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [ ]:
town = pd.get_dummies(df.town)

In [ ]:
merged = pd.concat([df, town], axis = 1)
merged = merged.drop(['town', 'west windsor'], axis = 1)

In [ ]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [ ]:
from sklearn.linear_model import LinearRegression as lr
reg = lr()
x = merged.drop(columns = ['price'])
y = merged['price']
reg.fit(x, y)

LinearRegression()

In [ ]:
reg.predict([[2800, 0, 1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([590775.63964739])

In [ ]:
reg.predict([[3400, 0,0 ]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([681241.66845839])

In [ ]:
print(f'{reg.score(x, y) *100:.2f}%')

95.74%

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
ohe = OneHotEncoder(categories=[0])
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [ ]:
x = dfle.drop(columns = 'price').values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [ ]:
y = dfle.price

In [ ]:
car = pd.read_csv("/carprices.csv")
car

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [ ]:
model = pd.get_dummies(car['Car Model'], drop_first = True)

In [ ]:
car = pd.concat([car, model], axis = 1)
car = car.drop(columns = 'Car Model')

In [ ]:
car

    Mileage  Sell Price($)  Age(yrs)  BMW X5  Mercedez Benz C class
0     69000          18000         6    True                  False
1     35000          34000         3    True                  False
2     57000          26100         5    True                  False
3     22500          40000         2    True                  False
4     46000          31500         4    True                  False
5     59000          29400         5   False                  False
6     52000          32000         5   False                  False
7     72000          19300         6   False                  False
8     91000          12000         8   False                  False
9     67000          22000         6   False                   True
10    83000          20000         7   False                   True
11    79000          21000         7   False                   True
12    59000          33000         5   False                   True

In [ ]:
x = car.drop(columns = 'Sell Price($)')
y = car['Sell Price($)']

In [ ]:
creg = lr()
creg.fit(x, y)

LinearRegression()

In [ ]:
creg.predict(x)

array([18705.2723644 , 35286.78445645, 24479.19112468, 41245.76426391,
       29882.98779056, 28023.6135243 , 30614.46818502, 21879.57266964,
       12182.34562104, 26183.72387884, 18929.31674102, 20409.80511857,
       30477.15426156])

In [ ]:
creg.score(x , y)

0.9417050937281083

In [ ]:
creg.predict([[45000, 4, 0, 1 ]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([36991.31721061])

In [ ]:
creg.predict([[86000, 7, 1, 0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11080.74313219])