<a href="https://colab.research.google.com/github/Omarctr/Machine-Learning/blob/main/naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("/content/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
from numpy import True_
df.drop(columns = ['Name','SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], inplace = True)
df

     PassengerId  Survived  Pclass     Sex   Age     Fare
0              1         0       3    male  22.0   7.2500
1              2         1       1  female  38.0  71.2833
2              3         1       3  female  26.0   7.9250
3              4         1       1  female  35.0  53.1000
4              5         0       3    male  35.0   8.0500
..           ...       ...     ...     ...   ...      ...
886          887         0       2    male  27.0  13.0000
887          888         1       1  female  19.0  30.0000
888          889         0       3  female   NaN  23.4500
889          890         1       1    male  26.0  30.0000
890          891         0       3    male  32.0   7.7500

[891 rows x 6 columns]

In [ ]:
temp = pd.get_dummies(df.Sex)
df = pd.concat([df, temp], axis = 1)
df

     PassengerId  Survived  Pclass     Sex   Age     Fare  female   male
0              1         0       3    male  22.0   7.2500   False   True
1              2         1       1  female  38.0  71.2833    True  False
2              3         1       3  female  26.0   7.9250    True  False
3              4         1       1  female  35.0  53.1000    True  False
4              5         0       3    male  35.0   8.0500   False   True
..           ...       ...     ...     ...   ...      ...     ...    ...
886          887         0       2    male  27.0  13.0000   False   True
887          888         1       1  female  19.0  30.0000    True  False
888          889         0       3  female   NaN  23.4500    True  False
889          890         1       1    male  26.0  30.0000   False   True
890          891         0       3    male  32.0   7.7500   False   True

[891 rows x 8 columns]

In [ ]:
df.drop(columns = 'Sex', inplace = True)
df

     PassengerId  Survived  Pclass   Age     Fare  female   male
0              1         0       3  22.0   7.2500   False   True
1              2         1       1  38.0  71.2833    True  False
2              3         1       3  26.0   7.9250    True  False
3              4         1       1  35.0  53.1000    True  False
4              5         0       3  35.0   8.0500   False   True
..           ...       ...     ...   ...      ...     ...    ...
886          887         0       2  27.0  13.0000   False   True
887          888         1       1  19.0  30.0000    True  False
888          889         0       3   NaN  23.4500    True  False
889          890         1       1  26.0  30.0000   False   True
890          891         0       3  32.0   7.7500   False   True

[891 rows x 7 columns]

In [ ]:
df.Age = df.Age.fillna(df.Age.mean())
df

     PassengerId  Survived  Pclass        Age     Fare  female   male
0              1         0       3  22.000000   7.2500   False   True
1              2         1       1  38.000000  71.2833    True  False
2              3         1       3  26.000000   7.9250    True  False
3              4         1       1  35.000000  53.1000    True  False
4              5         0       3  35.000000   8.0500   False   True
..           ...       ...     ...        ...      ...     ...    ...
886          887         0       2  27.000000  13.0000   False   True
887          888         1       1  19.000000  30.0000    True  False
888          889         0       3  29.699118  23.4500    True  False
889          890         1       1  26.000000  30.0000   False   True
890          891         0       3  32.000000   7.7500   False   True

[891 rows x 7 columns]

In [ ]:
from sklearn.model_selection import train_test_split

x = df.drop(columns = 'Survived')
y = df.Survived

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

In [ ]:
model.score(x_test, y_test)

0.7873134328358209

In [ ]:
y_test[:10]

709    1
439    0
840    0
720    1
39     1
290    1
300    1
333    0
208    1
136    1
Name: Survived, dtype: int64

In [ ]:
model.predict(x_test[:10])

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1])

In [ ]:
model.predict_proba(x_test[:10])

array([[0.99057538, 0.00942462],
       [0.97914766, 0.02085234],
       [0.98919336, 0.01080664],
       [0.01684124, 0.98315876],
       [0.0610953 , 0.9389047 ],
       [0.00194218, 0.99805782],
       [0.07336471, 0.92663529],
       [0.98680584, 0.01319416],
       [0.05725391, 0.94274609],
       [0.00940683, 0.99059317]])

In [ ]:
em = pd.read_csv("/content/spam.csv")
em.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
em.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [ ]:
em['spam'] = em.Category.map({'spam' : 1, 'ham' : 0})
em

     Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [ ]:
x = em.Message
y = em.spam

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
x_train_c = cv.fit_transform(x_train.values)
x_test_c = cv.transform(x_test.values)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()
mnb.fit(x_train_c, y_train)

MultinomialNB()

In [ ]:
emails = [
    'Hey mohan, can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exculsive offer just for you. Dont miss this reward!'
]
label = [0,1]

text_to_num = cv.transform(emails)
mnb.score(text_to_num, label)

1.0

In [ ]:
mnb.score(x_test_c, y_test)

0.9904306220095693

# **better way to transform text to numerical**

In [ ]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer' , CountVectorizer()),
    ('nb', MultinomialNB())
])

clf.fit(x_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
clf.score(x_test, y_test)

0.9904306220095693

# **exersice**

In [ ]:
from sklearn.datasets import load_wine
w = load_wine()
wine = pd.DataFrame(w.data, columns = w.feature_names)
wine['class'] = w.target
wine

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

In [ ]:
wine.groupby('class').median()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
class,,,,,,,,,,,,,
0,13.750,1.770,2.44,16.8,104.0,2.800,2.980,0.29,1.870,5.40,1.070,3.17,1095.0
1,12.290,1.610,2.24,20.0,88.0,2.200,2.030,0.37,1.610,2.90,1.040,2.83,495.0
2,13.165,3.265,2.38,21.0,97.0,1.635,0.685,0.47,1.105,7.55,0.665,1.66,627.5

In [ ]:
wine.drop(columns = ['ash', 'nonflavanoid_phenols', 'proanthocyanins',  'hue'], inplace = True)

In [ ]:
wine

,alcohol,malic_acid,alcalinity_of_ash,magnesium,total_phenols,flavanoids,color_intensity,od280/od315_of_diluted_wines,proline,class
0,14.23,1.71,15.6,127.0,2.80,3.06,5.64,3.92,1065.0,0
1,13.20,1.78,11.2,100.0,2.65,2.76,4.38,3.40,1050.0,0
2,13.16,2.36,18.6,101.0,2.80,3.24,5.68,3.17,1185.0,0
3,14.37,1.95,16.8,113.0,3.85,3.49,7.80,3.45,1480.0,0
4,13.24,2.59,21.0,118.0,2.80,2.69,4.32,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,20.5,95.0,1.68,0.61,7.70,1.74,740.0,2
174,13.40,3.91,23.0,102.0,1.80,0.75,7.30,1.56,750.0,2
175,13.27,4.28,20.0,120.0,1.59,0.69,10.20,1.56,835.0,2
176,13.17,2.59,20.0,120.0,1.65,0.68,9.30,1.62,840.0,2
177,14.13,4.10,24.5,96.0,2.05,0.76,9.20,1.60,560.0,2

In [ ]:
x = wine.drop(columns = 'class')
y = wine['class']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [ ]:
gauss = Pipeline([
    ('nb', GaussianNB())
])

multi = Pipeline([
    ('nb', MultinomialNB())
])
gauss.fit(x_train, y_train)
multi.fit(x_train, y_train)

Pipeline(steps=[('nb', MultinomialNB())])

In [ ]:
print(gauss.score(x_test, y_test))
multi.score(x_test, y_test)

0.9814814814814815

0.8518518518518519

In [ ]:
y_test[:10]

19     0
45     0
140    2
30     0
67     1
16     0
119    1
174    2
109    1
141    2
Name: class, dtype: int64

In [ ]:
gauss.predict(x_test[:10])

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2])